{adagrad_init_acc: 0.01, adam_lr: 0.0004, base_experiment: gcn_cnn, batch_size: 16,
  beam_size: 4, beta_l2: 0.0, concat_gcn_lstm: false, concat_with_word_embedding: true,
  dev_path: /home/ubuntu/finished_files/chunked/val_000.bin, emb_dim: 100,
  emb_trainable: true, exp_name: baseline_3_holle_small_save,
  flow_alone: false, flow_combined: false, glove_path: /home/ubuntu/glove/glove.6B.100d.txt,
  gpu_device_id: '0', hidden_dim: 256, log_root: /home/ubuntu/gttp_holle_logs, lr: 0.015,
  max_dec_steps: 6, max_enc_steps: 300, max_grad_norm: 2.0, max_query_steps: 65,
  max_to_keep: 7, min_dec_steps: 3, no_lstm_encoder: false, no_lstm_query_encoder: false,
  optimizer: adam, pointer_gen: true, query_encoder: true, query_gcn: false, query_gcn_dim: 128,
  query_gcn_dropout: 1.0, query_gcn_edge_dropout: 1.0, query_gcn_gating: false, query_gcn_layers: 1,
  query_gcn_skip: false, query_loop_dropout: 1.0, rand_unif_init_mag: 0.02, save_model_secs: 60,
  save_steps: 2125, simple_concat: false, stacked_lstm: false, stop_steps: 20000,
  test_path: /home/ubuntu/finished_files/chunked/test_000.bin, tf_example_format: true,
  train_path: /home/ubuntu/finished_files/chunked/train*3*.bin, trunc_norm_init_std: 1e-4,
  use_gating: true, use_gcn_before_lstm: false, use_gcn_lstm_parallel: false, use_glove: true,
  use_label_information: true, use_lstm: true, use_lstm_before_gcn: false, use_regularizer: false,
  use_save_at: false, use_stop_after: true, vocab_path: /home/ubuntu/finished_files/vocab,
  vocab_size: 25000, word_gcn: true, word_gcn_dim: 512, word_gcn_dropout: 1.0, word_gcn_edge_dropout: 0.75,
  word_gcn_gating: true, word_gcn_layers: 1, word_gcn_skip: true, word_loop_dropout: 1.0}



