{adagrad_init_acc: 0.01, adam_lr: 0.0004, base_experiment: gcn_cnn, batch_size: 16, use_regularizer: false, beta_l2: 0.0,
  beam_size: 4, concat_gcn_lstm: false, concat_with_word_embedding: true, dev_path: /home/riseadmin/gcn_finished_files/finished_files/chunked/val*,
  emb_dim: 100, emb_trainable: true, exp_name: 512_holle_batch_size_16_glove_True_adam_0.0004_model_tlstm_concat_interm_use_label_information_false_out_1,
  glove_path: /home/riseadmin/glove/glove.6B.100d.txt, gpu_device_id: '0', hidden_dim: 256,
  log_root: /home/riseadmin/gttp_logs, lr: 0.015, max_dec_steps: 60, max_enc_steps: 300,
  max_grad_norm: 2.0, max_query_steps: 65, max_to_keep: 7, min_dec_steps: 3, no_lstm_encoder: false,
  no_lstm_query_encoder: false, optimizer: adam, pointer_gen: true, query_encoder: true,
  query_gcn: false, query_gcn_dim: 128, query_gcn_dropout: 1.0, query_gcn_gating: false,
  query_gcn_layers: 1, rand_unif_init_mag: 0.02, save_steps: 50, save_model_secs: 60, simple_concat: false, stop_steps: 50000,
  test_path: /home/riseadmin/gcn_finished_files/finished_files/chunked/test*, tf_example_format: true,
  train_path: /home/riseadmin/gcn_finished_files/finished_files/chunked/train*, trunc_norm_init_std: 1e-4, use_gcn_before_lstm: false,
  use_gcn_lstm_parallel: false, use_glove: true, use_label_information: false, use_lstm: true,
  use_save_at: false, use_stop_after: true, vocab_path: /home/riseadmin/gcn_finished_files/finished_files/vocab,
  vocab_size: 25000, word_gcn: true, word_gcn_dim: 512, word_gcn_dropout: 1.0, word_gcn_gating: false, word_gcn_skip: false, query_gcn_skip: false,
  word_gcn_layers: 1, flow_alone: true, flow_combined: false}






